import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import * as Papa from 'papaparse';
import { StatsGroup } from '@/components/Stat'
import { createStyles } from '@mantine/core';
import SalaryHistogram from '@/components/Histogram';
import SalaryTable from '@/components/Table';

const inter = Inter({ subsets: ['latin'] })

const cleanNum = (val) => {
  if (!Number.isInteger(val)) {
    return parseFloat(val.replace(/,/g, ''))
  }
  return val
}



const useStyles = createStyles((theme) => ({
  pageContainer: {
    padding: '2rem'
  },
  pageHeader: {
    textAlign: 'center',
    fontSize: '24px'
  }
}));

export default function Home() {
  const [salaryData, setSalaryData] = useState(null);
  const styles = useStyles()
  useEffect(() => {
    const loadEmploymentData = () => {
      fetch('./K12AllStaffSalaryData.csv')
        .then(response => response.text())
        .then(responseText => {
          const parsed = Papa.parse(responseText, { header: true, dynamicTyping: true });
          const cleanedData = []
          parsed.data.forEach((row) => {
            const cleanedRow = {
              DistrictName: row["DistrictName"].trim(),
              Name: row["Name"].trim(),
              Duty: row["Duty"].trim(),
              SY2122: cleanNum(row["SY2021-22"]),
            }
            cleanedData.push(cleanedRow)
          })
          setSalaryData(cleanedData)
        });
    }
    loadEmploymentData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.classes.pageContainer}>
        <div>
          <h1 className={styles.classes.pageHeader}>Washinton Teacher Salaries 2021-2022</h1>
          <div>
            <StatsGroup data={[{ stats: 12321, title: "Median Salary", description: "This is the 50th percentile of teacher salaries." }]} />
          </div>
          <div>
            {salaryData && <SalaryHistogram data={salaryData} width={800} height={400}/>}
          </div>

          <div>
            {salaryData && <SalaryTable data={salaryData}/>}
          </div>

        </div>
      </main>
    </>
  )
}


